module.exports = {
  LOGIN: 'Login',
  SCAN_QR_CODE: 'ScanQrCode',
  EMPLOYE_LIST: 'EmployeList',
  VERIFICATION_CODE: 'VerificatioinCode',
  DETAIL: 'Detail',
  Otp: 'OTP',
  EMPLOYE_LIST_All: 'EmployeListAll',
  EMPLOYE_REJECTED_LIST: 'EmployeRejectList',
  EMPLOYE_APROVE_LIST: 'EmployeAprovetList',
  EMPLOYE_LIST_HOME: 'EmployeListHome',
  GAURD_LOGIN: 'GaurdsLogin',
  GENERATE_QR_CODE: 'GenerateQrCodeScreen',
  Home: 'Home',
  Dashboard: 'Dashboard',
};
