module.exports = {
  SCAN_QR_CODE: 'Scan QR Code',
  SCAN_QR_MSG: 'Scan the code on site or on your device to check in',
  SCAN_CODE: 'Scan Code',
  Manual_Entry: 'Manual Entry',
  CANCEL: 'Cancel',
  Done: 'Done',
  try_again: 'Scan Again',
  EMPLOYEE: 'Employees',
  VISITORS: 'Visitors',
  REJECT: 'Reject',
  Check_out: 'Check out',
  Approve :"Approve ",
  LOCATION_PERMISSION: 'Location Permission Required',
  LOCATION_PERMISSION_DESC:
    'This app requires location permission to function properly. Please enable the location permission.',
  ENABLE_PERMISSION: 'Enable Permission',
  CANCEL: 'Cancel',
  LOCATION_UNAVALABLE: 'Sorry! Location service UNAVAILABLE',
};
